### PR TITLE
Improve the GC graphs

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by hannesm** [comment]
I'm not sure about this... could the `graph` instead be passed in to `gc_quick_stat` / `gc_stat`?  the reason for this is that with my influxd outputter, I don't use `graph`, since I'm only writing measurements to a time series database - which is then used by e.g. grafana to select a set of measurements for a certain graph.

**Comment by samoht** [comment]
How do you decide which graph should contain which plot in influxdb? I think we need a way to gather plots together for every backends. For influxb it could generate the JSON config thingy for instance.

**Comment by hannesm** [comment]
I configure this by using grafana on the database of measurements -- the advantage is that I can dynamically add and remove measurements, include any sources (e.g. from the host system _and_ a unikernel), and also display a derived form (i.e. first derivation, useful for counters) or scale to a common measurement unit (ns instead of seconds, bytes instead of words, ...).  While parts of this could be done by importing json generated by metrics (how? at startup on console? every time a new source is registered?), cross-process-metrics (as mentioned, host system and unikernel) are not doable in this way.

**Comment by samoht** [comment]
Ideally, the metrics backends should be self-contained: eg. it's not very portable/flexible to have to go through an extra level of dynamic configuration via a different system. I understand that this is needed in practice for some use-cases, but that would be great if we could avoid that for simple use-cases.

I am happy to add any configuration that could be useful for the influxdb backend if that helps.

Note that the current `Graph` things can just be ignored by the influxdb backend if you don't need it.

**Comment by hannesm** [comment]
ok.  tbh, I don't understand the `graph` stuff.. please correct me if I'm wrong: at the definition of a field, you can specify a graph (`string`) where this field should show up in?
If there are now multiple libraries using metrics, how to figure out which graph names are already used/what they mean?
Can I have a field in multiple graphs?

isn't it the application programmer rather than the library developer who should decide which graph a field should be in?

**Comment by samoht** [comment]
>  at the definition of a field, you can specify a graph (string) where this field should show up in?

Every graph is an abstract value (of type `Graph.t`) which has a different ID (so there are no possibility of mixing things up).

> Can I have a field in multiple graphs?

Not at the moment but that should be easy to add. Which use-case do you have in mind?

> isn't it the application programmer rather than the library developer who should decide which graph a field should be in?

The application programmer is the one defining the field metrics right? If yes, when you define a new metrics, you also define how to group them together. By default, all the fields are separate, but you can add more constraint and force a few fields to appear on the same graph (for instance because they share the same units, or because it makes sense to always display them together).

Are you saying that you want the reporter/backends to also define how to group the fields?

**Comment by samoht** [comment]
Ok merging this now, I'm happy to change the API before the release. I am currently experimenting with it by instrumenting irmin, will see how it goes ...

**Pull request merged**
