### PR TITLE
Add an initial gnuplot backend

### PR DESCRIPTION
**Pull request by samoht**
And this seems to work! Need more documentation and a few tweaks in the Metrics
API.

A new file is generated for each pair: (source name * data field), with a graph
for each combination of tags. Run `make test` to see the result.

### CODE REVIEW

**Comment by samoht** [comment]
Here an example of the files produced by the [tests](https://github.com/samoht/metrics/blob/unix/test/unix/test.ml):

test-cpu

test-mem

ping @Mort for feedback regarding the graphviz rules :-)

Note: the Metric API will need more changes as we really need a way to document the fields to appear in the ylabel a bit more properly. The current way of getting the possible fields is a bit hackish, and we don't have guarantees that this list is not changing randomly.

**Comment by hannesm** [comment]
that's great.

> document the fields to appear in the ylabel a bit more properly

is a `tag` named `unit` (by convention) and value a `string` sufficient here (e.g. for temparature, it could be `°C`)

> current way of getting the possible fields is a bit hackish, and we don't have guarantees that this list is not changing randomly

I'd expect that the plotter would upfront know which fields it wants to graph. (for the influxdb case, I just insert everything into the database, and select which measurements I'm interested in in graphana)

**Comment by samoht** [comment]
I think I need to add an optional `~doc` argument here: https://github.com/samoht/metrics/blob/unix/test/unix/test.ml#L30 which will be propagated to replace the TODO on the `y` axis.

I agree that we can assume that the fields will always be the same; having to describe them upfront would be a bit annoying I think.

**Comment by samoht** [comment]
Merging this one now, will improve the API and the docs in later PRs.

**Pull request merged**
