### PR TITLE
add ocaml_runtime and ocaml_runtime_quick sources to Metrics

### PR DESCRIPTION
**Pull request by hannesm**
I'm not entirely sure where to put these two... since they only depend on `Gc`, I guess it is safe to put them here?

### CODE REVIEW

**Comment by samoht** [comment]
Thanks! The location is good but I am not sure about the names. Should these simply be `gc_stat` and `gc_quick_stat`?

**Comment by hannesm** [comment]
@samoht I'm easy about naming, and happy to use `gc_stat` / `gc_quick_stat` (will get back to this later today)

**Comment by hannesm** [comment]
rebased + renamed

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
